# SearXNG Settings for Maumachi Search
use_default_settings: true

server:
  base_url: https://my-search-engine-cc.onrender.com/
  method: "GET"
  cors: true

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: true
  - name: duckduckgo
    disabled: true
  - name: commoncrawl
    engine: commoncrawl
    shortcut: cc
    timeout: 5.0

