use_default_settings: true
engines:
  - name: google
    disabled: true
  - name: bing
    disabled: true
  - name: duckduckgo
    disabled: true
  - name: commoncrawl
    engine: commoncrawl
    shortcut: cc
    timeout: 5.0
